# Generated by Django 3.2.7 on 2021-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_link', models.CharField(max_length=255)),
                ('output_link', models.CharField(max_length=255, unique=True)),
                ('date_create_link', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
