# Generated by Django 3.2.7 on 2021-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shoter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылка'},
        ),
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='date_last_click',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='link',
            name='input_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='link',
            name='output_link',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
