# Generated by Django 3.2.7 on 2021-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shoter_app', '0002_auto_20210919_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
