# Generated by Django 3.2.7 on 2021-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shoter_app', '0003_alter_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество переходов'),
        ),
        migrations.AlterField(
            model_name='link',
            name='date_create_link',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='link',
            name='date_last_click',
            field=models.DateTimeField(default=None, verbose_name='Дата последнего перехода'),
        ),
        migrations.AlterField(
            model_name='link',
            name='input_link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='output_link',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
